### ISSUE TITLE
Tracking of importer JSON schema versions

### ISSUE THREAD

**Issue by vildead** [elixir-luxembourg/daisy#254]
At the moment, JSON schemas are included locally and if not found by importer, the remote version (master) is pulled.

To be able to track which version of JSON schema is used, the tag on schema repo should be used.

@jLebioda suggested:
```
The way I see it right now is that it could be done with:
  -.  SCHEMAS_REPOSITORY = 'https://github.com/elixir-luxembourg/json-schemas/tree/${tag}/schemas/' field in the settings and SCHAMES_VERSION = '0.1.0' field in the settings
-  SCHEMAS_URI = 'https://github.com/elixir-luxembourg/json-schemas/tree/0.1.0/schemas/' field in the settings
In validator - trying to get the local file with schema, and if it fails - trying to download it using HTTPS and the address from the settings

No submodules needed, no naming changes in schema repository; and not that much changes in DAISY anyways
```

Additionally:
- [x] include test the local version is in sync with remote one (pytest)
- [x] include check on every update that the local files are updated. If not, through ERROR
- [x] validating if the settings are fine when the application is bootstrapped, and not when the import is triggered

**Comment by vildead** [comment]
the issue is addressed in branch https://github.com/elixir-luxembourg/daisy/tree/254-tracking-of-importer-json-schema-versions

**Comment by vildead** [comment]
check will be performed on every startup
