### ISSUE TITLE
Record legal basis at the level of Projects rather than the Datasets

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#256]
We're currently recording GDPR legal basis of processing at the level of datasets. Experience in DPIAs have shown that legal basis is to be recorded at the level of Projects (per GDPR category of data processed).  Currently we record redundantly the same legal basis for all datasets of a project. Projects with many source cohorts have many datasets, hence lots of redundant data entry.

So we propose we keep lega basis at the Project level instead the Dataset level. Specifically the following changes to `core.models.LegalBasis`  woud be necessary:

- [ ] remove `dataset `reference
- [ ] add `project `reference.
- [ ] remove `data_declarations `reference
- [ ] make the move at the UI. move the legal basis box and edit forms (where nessary) from Dataset page to Project page.

**Comment by vildead** [comment]
to discuss later
